name: Create a new release
on:
  push:
    branches:
      - master

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - name: Get date
      run: echo ::set-env name=RELEASE_DATE::`date +"%d %B %Y"`
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.bump_version.outputs.new_tag }}
        release_name: Release ${{ steps.bump_version.outputs.new_tag }} (${{ github.sha }}) (${{ env.RELEASE_DATE }})
        body: >
            Latest change:
            ${{ github.event.commits[0].message }}
    - name: Dispatch event to trigger upload
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        event-type: release_created
        client-payload: '{"upload_url": "${{ steps.create_release.outputs.upload_url }}"}'
        
