name: Upload release assets
on:
  repository_dispatch:
    types: [release_created]

jobs:
  upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: file.linux
          - os: macos-latest
            asset_name: file.osx
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: echo "Building on ${{ matrix.os }}"
      - name: Upload build assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.client_payload.upload_url}}
          asset_path: test_file.rs
          asset_name: ${{ matrix.asset_name }}
          content-type: application/example
